"""Private, self-contained avatars generated by the embedded scanner."""
import hashlib
import json
import math
import re
import struct
import uuid

MAX_MODEL_BYTES = 64 * 1024 * 1024


def name_key(value):
    return re.sub(r'[^a-z0-9]', '', str(value).lower().split(':')[-1])


def validate_model(raw):
    """Reject external resources and unanimated exports before replacing a profile."""
    try:
        if not 20 <= len(raw) <= MAX_MODEL_BYTES:
            raise ValueError('Размер модели должен быть не больше 64 МБ.')
        magic, version, length = struct.unpack_from('<4sII', raw)
        if magic != b'glTF' or version != 2 or length != len(raw):
            raise ValueError('Сканер вернул повреждённую модель.')
        offset, chunks = 12, []
        while offset < length:
            size, kind = struct.unpack_from('<II', raw, offset)
            offset += 8
            if size % 4 or offset + size > length:
                raise ValueError('Повреждённые данные модели.')
            chunks.append((kind, raw[offset:offset + size]))
            offset += size
        if len(chunks) != 2 or [c[0] for c in chunks] != [0x4E4F534A, 0x004E4942]:
            raise ValueError('Модель должна содержать геометрию и текстуры в одном файле.')
        if len(chunks[0][1]) > 4 * 1024 * 1024:
            raise ValueError('Слишком сложное описание модели.')
        doc = json.loads(chunks[0][1])
        if not isinstance(doc, dict) or doc.get('asset', {}).get('version') != '2.0':
            raise ValueError('Некорректная версия модели.')
        buffers = doc.get('buffers', [])
        if len(buffers) != 1 or 'uri' in buffers[0] or not 0 < buffers[0]['byteLength'] <= len(chunks[1][1]):
            raise ValueError('Внешние файлы модели не разрешены.')
        if any('uri' in image or image.get('mimeType') not in ('image/png', 'image/jpeg') for image in doc.get('images', [])):
            raise ValueError('Текстуры должны быть встроенными PNG/JPEG.')
        supported = {'KHR_materials_unlit', 'KHR_materials_pbrSpecularGlossiness', 'KHR_texture_transform',
                     'KHR_materials_clearcoat', 'KHR_materials_transmission', 'KHR_materials_ior',
                     'KHR_materials_specular', 'KHR_materials_sheen', 'KHR_materials_volume', 'KHR_mesh_quantization'}
        if set(doc.get('extensionsRequired', [])) - supported:
            raise ValueError('Сканер использовал неподдерживаемое сжатие модели.')
        views = doc.get('bufferViews', [])
        for view in views:
            start, size = view.get('byteOffset', 0), view['byteLength']
            if view.get('buffer', 0) != 0 or type(start) is not int or type(size) is not int or start < 0 or size < 0 or start + size > buffers[0]['byteLength']:
                raise ValueError('Геометрия выходит за границы файла.')
        nodes, meshes, skins = doc.get('nodes', []), doc.get('meshes', []), doc.get('skins', [])
        if not nodes or len(nodes) > 2048 or not meshes or len(meshes) > 256:
            raise ValueError('Модель слишком сложная или не содержит геометрии.')
        # Prevent cyclic hierarchies and repeated parents before GLTFLoader traverses them.
        parents, visiting, visited = {}, set(), set()
        def visit(index):
            if type(index) is not int or not 0 <= index < len(nodes) or index in visiting:
                raise ValueError('Некорректная иерархия модели.')
            if index in visited:
                return
            visiting.add(index)
            for child in nodes[index].get('children', []):
                if child in parents:
                    raise ValueError('У части модели несколько родителей.')
                parents[child] = index
                visit(child)
            visiting.remove(index)
            visited.add(index)
        for index in range(len(nodes)):
            visit(index)
        for node in nodes:
            for field in ('translation', 'rotation', 'scale', 'matrix'):
                if field in node and not all(type(x) in (float, int) and math.isfinite(x) for x in node[field]):
                    raise ValueError('Некорректные пропорции модели.')
        joints = {joint for skin in skins for joint in skin.get('joints', [])}
        if any(type(j) is not int or not 0 <= j < len(nodes) for j in joints):
            raise ValueError('Повреждённый скелет модели.')
        bone_names = {name_key(nodes[j].get('name', '')) for j in joints}
        if not {'head', 'neck'} <= bone_names:
            raise ValueError('Нужна модель с подвижной головой и шеей.')
        accessors = doc.get('accessors', [])
        if len(accessors) > 20000:
            raise ValueError('Слишком сложная геометрия.')
        widths = {'SCALAR': 1, 'VEC2': 2, 'VEC3': 3, 'VEC4': 4, 'MAT2': 4, 'MAT3': 9, 'MAT4': 16}
        sizes = {5120: 1, 5121: 1, 5122: 2, 5123: 2, 5125: 4, 5126: 4}
        for accessor in accessors:
            count = accessor['count']
            width = widths[accessor['type']] * sizes[accessor['componentType']]
            if type(count) is not int or not 0 <= count <= 500000:
                raise ValueError('Слишком много точек в модели.')
            if 'sparse' in accessor:
                raise ValueError('Сканер должен экспортировать обычные формы лица без sparse-сжатия.')
            if 'bufferView' in accessor:
                view = views[accessor['bufferView']]
                start, stride = accessor.get('byteOffset', 0), view.get('byteStride', width)
                if start < 0 or stride < width or start + max(0, count - 1) * stride + (width if count else 0) > view['byteLength']:
                    raise ValueError('Некорректные данные геометрии.')
        targets, vertices = set(), 0
        for mesh in meshes:
            names = mesh.get('extras', {}).get('targetNames', [])
            for primitive in mesh.get('primitives', []):
                position = accessors[primitive['attributes']['POSITION']]
                vertices += position['count']
                if position['type'] != 'VEC3' or 'bufferView' not in position:
                    raise ValueError('Модель не содержит объёмной геометрии.')
                if len(names) != len(primitive.get('targets', [])):
                    if primitive.get('targets'):
                        raise ValueError('Не подписаны формы лица.')
                targets.update(name_key(name) for name in names)
        if not 3 <= vertices <= 500000:
            raise ValueError('Слишком сложная модель для телефона.')
        if not {'jawopen', 'eyeblinkleft', 'eyeblinkright'} <= targets:
            raise ValueError('Выберите в сканере анимируемый аватар T2: нужен подвижный рот и моргание.')
        return {'vertices': vertices, 'bytes': len(raw), 'sha256': hashlib.sha256(raw).hexdigest()}
    except (KeyError, TypeError, IndexError, struct.error, UnicodeError, json.JSONDecodeError, RecursionError) as exc:
        raise ValueError('Сканер вернул повреждённую модель. Повторите создание аватара.') from exc


def save_model(runtime, raw, provider='parentai-server'):
    metadata = validate_model(raw)
    from runtime import atomic_json
    with runtime.lock:
        filename = 'avatar-' + uuid.uuid4().hex + '.glb'
        path = runtime.data / filename
        path.write_bytes(raw)
        profile = {'version': 6, 'provider': provider, 'model': filename, **metadata}
        try:
            atomic_json(runtime.data / 'avatar.json', profile)
        except Exception:
            path.unlink(missing_ok=True)
            raise
        for previous in runtime.data.glob('avatar-*.glb'):
            if previous != path:
                previous.unlink(missing_ok=True)
        return profile


def model_path(runtime):
    with runtime.lock:
        profile = runtime.avatar()
        filename = profile.get('model', '') if isinstance(profile, dict) and profile.get('version') == 6 else ''
        if not re.fullmatch(r'avatar-[0-9a-f]{32}\.glb', filename):
            raise ValueError('Сначала создайте новый аватар.')
        path = runtime.data / filename
        if not path.is_file():
            raise ValueError('Сохранённый аватар не найден. Повторите сканирование.')
        return path


def scanner_status():
    return {'provider': 'ParentAI', 'enabled': True, 'mode': 'on-device',
            'message': 'Сканирование и построение модели выполняются на устройстве.'}
